### ISSUE TITLE
APK download?

### ISSUE THREAD

**Issue by ThreeDeeJay** [raphaelm/android-barcode-keyboard#7]
Is the APK available for download anywhere? I know according to https://github.com/raphaelm/android-barcode-keyboard/issues/1 it was gonna be added to F-Droid but apparently that never happened.
Also, I tried building the APK using 2 different methods, but failed so I gave up😅

**Comment by raphaelm** [comment]
I have now uploaded the APK here: https://github.com/raphaelm/android-barcode-keyboard/releases/tag/1.0

**Comment by ThreeDeeJay** [comment]
Thanks so much, mate. Works like a charm! 👍
Just used it to open this page on my phone to reply👌
